#!/bin/bash
#
# CodeRaft updater
#
# Self-updates from the installer repo, then compares image digests before
# pulling new ones. If something breaks, runs rollback.sh.
#
set -e

DASHBOARD_API="${DASHBOARD_API:-http://localhost:3000}"
ADMIN_TOKEN="${ADMIN_TOKEN:-}"
BACKUP_DIR="${BACKUP_DIR:-./dashboard_data/backups}"
HEALTHCHECK_RETRIES="${HEALTHCHECK_RETRIES:-30}"
HEALTHCHECK_DELAY="${HEALTHCHECK_DELAY:-3}"
INSTALL_DIR="${INSTALL_DIR:-$PWD}"

# ── ADMIN_TOKEN auto-discovery ────────────────────────────────────────────
# Priority order:
#   1. $ADMIN_TOKEN env var (already set above)
#   2. .env files (INSTALL_DIR, /etc/coderaft, ~/.coderaft)
#   3. Plain token files (single word)
#   4. Mounted Docker secret
# If nothing is found → continue; snapshot/notify are skipped with a warning.
# IMPORTANT: NEVER echo the discovered token.
discover_admin_token() {
    if [ -n "${ADMIN_TOKEN:-}" ]; then
        printf '%s' "$ADMIN_TOKEN"
        return 0
    fi
    local env_file val
    for env_file in "$INSTALL_DIR/.env" "/etc/coderaft/.env" "$HOME/.coderaft/.env"; do
        if [ -f "$env_file" ] && [ -r "$env_file" ]; then
            val=$(grep -E '^[[:space:]]*ADMIN_TOKEN=' "$env_file" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"' | tr -d "'" | tr -d '[:space:]')
            if [ -n "$val" ]; then
                printf '%s' "$val"
                return 0
            fi
        fi
    done
    local token_file
    for token_file in "/etc/coderaft/admin_token" "$HOME/.coderaft/admin_token" "/run/secrets/admin_token"; do
        if [ -f "$token_file" ] && [ -r "$token_file" ]; then
            val=$(tr -d '[:space:]' < "$token_file" 2>/dev/null)
            if [ -n "$val" ]; then
                printf '%s' "$val"
                return 0
            fi
        fi
    done
    # 5. Auto-discovery from running dashboard-api container (preferred,
    #    avoids any manual setup — dashboard-api auto-generates the token
    #    at boot and persists it to /data/admin_token).
    if (cd "$INSTALL_DIR" 2>/dev/null && docker compose ps --services 2>/dev/null | grep -q '^dashboard-api$'); then
        val=$(cd "$INSTALL_DIR" && docker compose exec -T dashboard-api cat /data/admin_token 2>/dev/null < /dev/null | tr -d '[:space:]')
        if [ -n "$val" ]; then
            printf '%s' "$val"
            return 0
        fi
    fi
    return 1
}

if [ -z "$ADMIN_TOKEN" ]; then
    if discovered=$(discover_admin_token); then
        ADMIN_TOKEN="$discovered"
    fi
    unset discovered
fi

# ── Docker platform detection ──────────────────────────────────────────────
# Docker Desktop on Mac M-series resolves strictly to linux/arm64/v8 by
# default, which fails on manifests that only expose linux/arm64. Same goes
# for various Docker Engine versions. Force DOCKER_DEFAULT_PLATFORM based
# on the host arch to work around this bug.
if [ -z "$DOCKER_DEFAULT_PLATFORM" ]; then
    HOST_ARCH=$(uname -m 2>/dev/null || echo "")
    case "$HOST_ARCH" in
        arm64|aarch64) export DOCKER_DEFAULT_PLATFORM="linux/arm64" ;;
        x86_64|amd64)  export DOCKER_DEFAULT_PLATFORM="linux/amd64" ;;
    esac
fi

# ── Self-update both update.sh and rollback.sh (with re-exec) ──────────────
if [ -z "$CODERAFT_UPDATE_REEXEC" ]; then
    echo "  Checking for script updates..."
    REFRESHED=0
    for name in update.sh rollback.sh; do
        LATEST=$(curl -fsSL "https://raw.githubusercontent.com/LiamJ74/coderaft-installer/master/scripts/$name" 2>/dev/null)
        if [ -n "$LATEST" ] && [ ${#LATEST} -gt 50 ]; then
            echo "$LATEST" > "$name.tmp"
            if ! cmp -s "$name" "$name.tmp" 2>/dev/null; then
                mv "$name.tmp" "$name" && chmod +x "$name"
                echo "  $name refreshed"
                [ "$name" = "update.sh" ] && REFRESHED=1
            else
                rm -f "$name.tmp"
            fi
        fi
    done
    if [ "$REFRESHED" = "1" ] && [ -x "./update.sh" ]; then
        echo "  Re-executing the updated script..."
        export CODERAFT_UPDATE_REEXEC=1
        exec bash ./update.sh "$@"
    fi
fi

# ── Self-heal compose YAML ────────────────────────────────────────────────
# Detects a docker-compose.override.yml generated by an older dashboard-api
# version with a broken YAML serializer. Without this, every `docker compose
# ps/up/down` fails with "yaml: line N: ..." and the oneliner cannot do
# anything. Recovery: back up the broken override, pull the latest
# dashboard-api, start it alone (with postgres+redis); it regenerates a
# clean override, then we continue normally.
echo ""
echo "  Checking compose integrity..."
if ! docker compose ps >/dev/null 2>&1; then
    echo "  ⚠ docker-compose.override.yml appears corrupted — auto-recovery..."
    if [ -f "docker-compose.override.yml" ]; then
        cp docker-compose.override.yml "docker-compose.override.yml.broken-$(date +%Y%m%d_%H%M%S)" 2>/dev/null || true
        rm -f docker-compose.override.yml
        echo "    ✓ override backed up + removed"
    fi
    docker pull ghcr.io/liamj74/coderaft-dashboard-api:latest >/dev/null 2>&1 || true
    if docker compose up -d postgres redis dashboard-api >/dev/null 2>&1; then
        sleep 6
        if docker compose ps >/dev/null 2>&1; then
            echo "    ✓ compose repaired"
        else
            echo "  ERROR: self-heal failed. Inspect docker-compose.override.yml manually."
            exit 1
        fi
    else
        echo "  ERROR: cannot restart dashboard-api. Check Docker Engine."
        exit 1
    fi
else
    echo "  ✓ compose OK"
fi

# ── Host capture sanity check (Live Capture / Frame Analyzer) ─────────────
# When the operator picked native capture (CODERAFT_HOST_OS=windows|macos),
# Ravenscan expects a host daemon on 127.0.0.1:7777 reachable via
# host.docker.internal. We probe it from inside an alpine one-shot — if the
# probe fails we *warn* (never block: the host may simply be powered off
# during the update window, or the operator may not have run the wizard
# yet). The user can fix this from the dashboard's Setup → Live Capture tab.
echo ""
echo "  Live Capture sanity check..."
HOST_OS_VALUE=""
if [ -f .env ]; then
    HOST_OS_VALUE=$(grep -E '^\s*CODERAFT_HOST_OS\s*=' .env 2>/dev/null | tail -1 | cut -d= -f2 | tr -d '"' | tr -d "'" | tr '[:upper:]' '[:lower:]' | xargs)
fi
case "$HOST_OS_VALUE" in
    windows|macos)
        # Curl --connect-timeout keeps the probe under 4s on offline hosts.
        if docker run --rm --add-host=host.docker.internal:host-gateway \
            curlimages/curl:8.10.1 -fsS --connect-timeout 3 --max-time 4 \
            "http://host.docker.internal:7777/health" >/dev/null 2>&1; then
            echo "  ✓ Native capture daemon reachable (CODERAFT_HOST_OS=$HOST_OS_VALUE)"
        else
            echo "  ⚠ CODERAFT_HOST_OS=$HOST_OS_VALUE but the native daemon is not answering on 127.0.0.1:7777."
            echo "     Frame Analyzer may show empty captures. Open the dashboard → Setup → Live Capture"
            echo "     to (re)install the host daemon. Continuing the update."
        fi
        ;;
    linux|"")
        # No-op: Linux uses the in-Docker sidecar; missing var = default behaviour.
        ;;
    *)
        echo "  ⚠ CODERAFT_HOST_OS='$HOST_OS_VALUE' is not a recognised value (windows|macos|linux). Ignored."
        ;;
esac

# ── Mandatory pre-update backup ───────────────────────────────────────────
# If pg_dump fails → block the update (no backup = no update).
echo ""
echo "  Pre-update backup..."
mkdir -p "$BACKUP_DIR"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BACKUP_FILE="$BACKUP_DIR/preupdate-${TIMESTAMP}.sql.gz"

if docker compose ps postgres --quiet 2>/dev/null | grep -q .; then
    # `< /dev/null` is CRITICAL: without it, `docker compose exec -T` inherits
    # stdin, and when the updater is launched via `curl … | bash`, stdin = pipe
    # containing the rest of the script that bash has not read yet. docker exec
    # drains those bytes → bash hits EOF prematurely and the script exits
    # silently after "Backup saved" (no error, no rollback).
    if docker compose exec -T postgres pg_dumpall -U coderaft < /dev/null 2>/dev/null | gzip > "$BACKUP_FILE"; then
        echo "  Backup saved: $BACKUP_FILE"
    else
        echo "  ERROR: pg_dump failed. Update cancelled (no backup = no update)."
        echo "  Check that the postgres container is healthy: docker compose ps"
        exit 1
    fi
else
    echo "  PostgreSQL not detected — backup skipped (dashboard without DB)."
fi

# ── Capture recovery snapshot via dashboard-api ───────────────────────────
echo "  Capturing recovery snapshot..."
if [ -n "$ADMIN_TOKEN" ]; then
    curl -fsS -X POST "$DASHBOARD_API/api/dashboard/recovery/snapshots" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $ADMIN_TOKEN" \
        -d '{"reason":"pre-update"}' > /dev/null \
        && echo "    Snapshot saved." \
        || echo "    Snapshot failed (auto-snapshot will run again at next deploy)."
else
    echo "    [warn] ADMIN_TOKEN not found — snapshot skipped."
    echo "    (set ADMIN_TOKEN env, or place token in $INSTALL_DIR/.env, /etc/coderaft/admin_token, ~/.coderaft/admin_token, or /run/secrets/admin_token)"
fi

# ── Compare digests before pulling ────────────────────────────────────────
# Avoids pulling unnecessarily when nothing has changed on GHCR.
# Fallback: if skopeo is missing, use docker pull --quiet + compare the ID.
echo ""
echo "  Checking for available updates..."

COMPOSE_ARGS=()
if [ -f "./docker-compose.override.yml" ]; then
    COMPOSE_ARGS=(-f ./docker-compose.yml -f ./docker-compose.override.yml)
fi

IMAGES_TO_UPDATE=()

while IFS= read -r img; do
    [ -z "$img" ] && continue
    # Fetch local digest (Image ID sha256:...)
    local_digest=$(docker inspect "$img" --format '{{.Id}}' 2>/dev/null || echo "missing")

    if [ "$local_digest" = "missing" ]; then
        echo "    $img: not present locally → will pull"
        IMAGES_TO_UPDATE+=("$img")
        continue
    fi

    # Try skopeo first (more reliable)
    if command -v skopeo &>/dev/null; then
        remote_digest=$(skopeo inspect "docker://$img" 2>/dev/null | grep -o '"Digest":"[^"]*"' | head -1 | cut -d'"' -f4 || echo "")
    else
        # Fallback: dry-run pull (docker pull --quiet compares the image ID).
        # Tag the current image, pull, then compare IDs.
        remote_digest=""
    fi

    if [ -n "$remote_digest" ] && [ "$remote_digest" = "$local_digest" ]; then
        echo "    $img: up to date"
    else
        echo "    $img: update available"
        IMAGES_TO_UPDATE+=("$img")
    fi
done < <(docker compose "${COMPOSE_ARGS[@]}" config --images 2>/dev/null)

if [ ${#IMAGES_TO_UPDATE[@]} -eq 0 ]; then
    echo ""
    echo "  Everything is up to date. No action needed."
    echo ""
    exit 0
fi

echo ""
echo "  ${#IMAGES_TO_UPDATE[@]} image(s) to update."

# ── Refresh license keys (drift "superseded") ─────────────────────────────
# When the License Server resigns a license (e.g. feature added, extension,
# key rotation), the server returns 403 "License has been superseded by a
# newer version" for any request using the old key. The product-side fix
# prioritizes DB > env, but on a fresh deploy or after a volume reset, only
# the env key exists. So we refresh it here, in-place in
# docker-compose.override.yml, BEFORE `docker compose up`.
#
# Strategy: POST /api/licenses/validate with the local key; if the response
# contains a different `latest_license_key`, write it into the override
# (with a .bak backup). We never fail the update because of this (License
# Server down → continue with the local key; the runtime will handle 403).
refresh_license() {
    local env_var="$1"   # LICENSE_KEY / RAVENSCAN_LICENSE_KEY / REDFOX_LICENSE_KEY
    local override_file="$INSTALL_DIR/docker-compose.override.yml"
    [[ ! -f "$override_file" ]] && return 0
    grep -qE "^[[:space:]]*-?[[:space:]]*${env_var}=" "$override_file" || return 0

    local current_key
    current_key=$(grep -E "^[[:space:]]*-?[[:space:]]*${env_var}=" "$override_file" \
        | head -1 \
        | sed -E "s/^[[:space:]]*-?[[:space:]]*${env_var}=//" \
        | tr -d '"' | tr -d "'" | xargs)
    [[ -z "$current_key" || "$current_key" == "UNCONFIGURED" ]] && return 0

    local server="${LICENSE_SERVER_URL:-https://license.coderaft.io}"
    local response
    response=$(curl -s --max-time 10 -X POST "${server}/api/licenses/validate" \
        -H "Content-Type: application/json" \
        -d "{\"license_key\":\"$current_key\"}" 2>/dev/null) || return 0
    [[ -z "$response" ]] && return 0

    local latest=""
    if command -v jq &>/dev/null; then
        latest=$(echo "$response" | jq -r '.latest_license_key // empty' 2>/dev/null)
    else
        latest=$(echo "$response" \
            | grep -oE '"latest_license_key"[[:space:]]*:[[:space:]]*"[^"]+"' \
            | head -1 \
            | sed -E 's/.*"latest_license_key"[[:space:]]*:[[:space:]]*"([^"]+)".*/\1/')
    fi

    if [[ -n "$latest" && "$latest" != "$current_key" ]]; then
        cp "$override_file" "${override_file}.bak"
        # awk: replace ALL occurrences (entraguard-api + entraguard-worker
        # may share the same key across multiple services).
        awk -v var="$env_var" -v key="$latest" '
            {
                pat = "^[[:space:]]*-?[[:space:]]*" var "="
                if ($0 ~ pat) {
                    match($0, /^[[:space:]]*-?[[:space:]]*/)
                    pad = substr($0, 1, RLENGTH)
                    print pad var "=" key
                    next
                }
                print
            }
        ' "${override_file}.bak" > "$override_file"
        echo "  🔄 License refreshed for ${env_var}"
        return 1  # signal: restart needed
    fi
    return 0
}

refresh_all_licenses() {
    echo ""
    echo "  ▶ Checking for license drift..."
    local restart_needed=0
    for var in LICENSE_KEY RAVENSCAN_LICENSE_KEY REDFOX_LICENSE_KEY; do
        refresh_license "$var" || restart_needed=1
    done
    if [ "$restart_needed" -eq 0 ]; then
        echo "  ✅ All licenses are up to date"
    else
        echo "  ⚠️  At least one license was refreshed; services will be restarted"
    fi
    return 0
}

refresh_all_licenses || true

# ── Renew local HTTPS certs if older than 80 days ─────────────────────────
# Preserve user-provided certs untouched. Only auto-renew the ones we
# generated (mkcert) before they hit mkcert's 825d expiry. Failure is
# non-fatal — the dashboard remains reachable on http://localhost:3000.
renew_local_https() {
    local cert="$INSTALL_DIR/caddy_certs/coderaft.local.pem"
    local key="$INSTALL_DIR/caddy_certs/coderaft.local-key.pem"
    [ -f "$cert" ] || return 0
    [ -f "$key" ]  || return 0
    if find "$cert" -mtime -80 2>/dev/null | grep -q .; then
        return 0
    fi
    if ! command -v mkcert &>/dev/null; then
        echo "  ⚠ mkcert absent — cannot renew local HTTPS certs (still valid until mkcert default 825d)."
        return 0
    fi
    echo "  Renewing local HTTPS cert (>80d old)…"
    mkcert \
        -cert-file "$cert" \
        -key-file  "$key" \
        coderaft.local "*.coderaft.local" localhost 127.0.0.1 ::1 >/dev/null 2>&1 \
        && chmod 600 "$key" \
        && echo "  ✓ Local HTTPS cert renewed" \
        || echo "  ⚠ Cert renewal failed — keeping previous cert"
}

renew_local_https || true

# ── AGGRESSIVE Docker image cache invalidation ────────────────────────────
# Docker Desktop multi-arch bug: when a new manifest list is pushed to GHCR,
# `docker pull` may report "Image is up to date" even though the local and
# remote digests differ. This is because Docker Desktop caches the
# tag→digest resolution.
#
# Fix: for each Coderaft image, stop the containers using it, force-untag
# AND remove the image by ID. The next pull is then forced to re-resolve
# the remote manifest list and actually download.
echo "  Aggressive Coderaft image cache invalidation..."
for img in "${IMAGES_TO_UPDATE[@]}"; do
    case "$img" in
        ghcr.io/liamj74/*)
            # 1. Stop containers running on this image
            container_ids=$(docker ps -q --filter "ancestor=$img" 2>/dev/null || true)
            if [ -n "$container_ids" ]; then
                docker stop $container_ids >/dev/null 2>&1 || true
                docker rm -f $container_ids >/dev/null 2>&1 || true
            fi
            # 2. Untag (releases the :latest name)
            docker rmi -f "$img" >/dev/null 2>&1 || true
            # 3. Also remove by ID (in case the image survives untagged)
            image_ids=$(docker images --format '{{.ID}}' "$img" 2>/dev/null || true)
            if [ -n "$image_ids" ]; then
                echo "$image_ids" | while read -r iid; do
                    [ -n "$iid" ] && docker rmi -f "$iid" >/dev/null 2>&1 || true
                done
            fi
            ;;
    esac
done

# ── Pull and recreate ─────────────────────────────────────────────────────
# Note: `--pull always` on `up` retried a per-service GHCR manifest check at
# redeploy time, which caused timeouts on slow connections. We now rely on
# the `docker rmi -f` + `docker compose pull` above to guarantee that the
# :latest tag points to the new image before `up`.
echo "  Downloading new images..."
docker compose "${COMPOSE_ARGS[@]}" pull \
    && docker compose "${COMPOSE_ARGS[@]}" up -d --force-recreate --remove-orphans

# ── Post-update healthcheck ───────────────────────────────────────────────
echo ""
echo "  Post-update health check..."
HEALTH_OK=1
HEALTH_URL="$DASHBOARD_API/api/health"

for i in $(seq 1 "$HEALTHCHECK_RETRIES"); do
    # -sS without -f: capture the HTTP code even on 4xx/5xx instead of an
    # exit code !=0 which would concatenate "0" (gave "5020" instead of "502").
    HTTP_CODE=$(curl -sS -o /dev/null -w "%{http_code}" "$HEALTH_URL" 2>/dev/null || echo "000")
    if [ "$HTTP_CODE" -ge 200 ] && [ "$HTTP_CODE" -lt 500 ]; then
        echo "  Dashboard API healthy (HTTP $HTTP_CODE) after ${i} attempt(s)."
        HEALTH_OK=0
        break
    fi
    echo "  Attempt $i/$HEALTHCHECK_RETRIES — HTTP $HTTP_CODE. Waiting ${HEALTHCHECK_DELAY}s..."
    sleep "$HEALTHCHECK_DELAY"
done

if [ "$HEALTH_OK" -ne 0 ]; then
    echo ""
    echo "  ERROR: healthcheck failed after $HEALTHCHECK_RETRIES attempts."
    echo "  Triggering automatic rollback..."
    if [ -x "./rollback.sh" ]; then
        bash ./rollback.sh
    else
        echo "  rollback.sh not found. Manual rollback required."
        echo "  Command: docker compose down && docker compose up -d"
    fi
    exit 1
fi

# ── Post-update notification ──────────────────────────────────────────────
if [ -n "$ADMIN_TOKEN" ]; then
    curl -fsS -X POST "$DASHBOARD_API/api/platform/update/notify" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $ADMIN_TOKEN" \
        -d '{"status":"done","source":"update.sh"}' > /dev/null 2>&1 || true
fi

echo ""
echo "  Update successful! Dashboard: http://localhost:3000"
echo "  If something went wrong: ./rollback.sh"
echo "  (or: curl -fsSL https://install.coderaft.io/rollback | bash)"
